{
 "title": "custom-metrics-hpa-demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info,namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "rabbitmq_cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\"},rabbitmq_cluster)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(rabbitmq_identity_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_global_publishers * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "rabbitmq queue messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_redelivered_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_auto_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_auto_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_manual_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_consumers * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "k8s HPA Status Condution",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_condition{horizontalpodautoscaler=\"consumer-deployment-hpa\",job=\"kube-state-metrics\"}"
    }
   ]
  },
  {
   "title": "k8s replicas ready by deployment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"consumer-deployment\",job=\"kube-state-metrics\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"producer-deployment\",job=\"kube-state-metrics\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}