apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-deployment-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # - type: Pods
  #   pods:
  #     metric:
  #       name: rabbitmq_queue_length
  #     target:
  #       type: Value
  #       averageValue: 50m
  - type: Object
    object:
      describedObject:
        kind: Service
        name: rabbitmq-service
      metric:
        name: rabbitmq_queue_length
      target:
        type: Value
        value: "50"