---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.11
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "200Mi"
        env:
        - name: "GF_DEFAULT_APP_MODE"
          value: "development"
        - name: "GF_AUTH_ANONYMOUS_ENABLED"
          value: "true"
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-dashboard-provider
          - mountPath: /var/lib/grafana/dashboards
            name: custom-metrics-hpa-demo-dashboard
            readOnly: false
      volumes:
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasource-config
        - name: grafana-dashboard-provider
          configMap:
              defaultMode: 420
              name: grafana-dashboard-provider
        - name: custom-metrics-hpa-demo-dashboard
          configMap:
              defaultMode: 420
              name: custom-metrics-hpa-demo-dashboard
