---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: grafana-ui
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer